### ISSUE TITLE
Peer Review (Kopia från mail)

### ISSUE THREAD

**Issue by lr222gw** [al223ec/1DV450-Registreringsapplikation#1]
Hej! 
Har kollat över din kod nu, den ser bra ut! 

Problem:
Jag kom så långt att jag kunde köra "bundle install", men när jag försökte köra "rails s" så fick jag ett error om bcrypt.

Löste problemet genom att byta ut föregående raden:
"gem 'bcrypt',               '3.1.7'"

mot raden:

gem 'bcrypt', '~> 3.1.9' 
(Det var alltså fel version på bcrypt... som ej fungerade med windows..)

Samma sak gällde  sqlite3, lösningen blev följande:
gem 'sqlite3',     '1.3.9'
byttes ut till:
gem 'sqlite3',     '1.3.10'

Körde "rake db:migrate" och "rake db:seed" följt av  "rails s".
Nu fungerade sidan och allt som det skulle.

Översikt:
Applikationen ser mycket bra ut! 
Den fungerar klockrent och hade inga problem att testa allt man kunde göra.
Enda problemen jag hade var pågrund av Ruby på windows 7. 
Koden är enkel att läsa och skriven enligt tänket "feta modeller, smala kontrollrar" vilket som är toppen då vi kodar i Ruby! 
Jag är ingen expert på RoR men jag lade inte märke till några konstigheter gällande koden eller uppdelingen av uppgifter mellan kontrollrarna och modellerna. 
Det verkar som du nyttjat RoR väl, då jag ser att du använt funktioner som jag itne lagt märke till,Tex "will_paginate" i "index.html.erb".
Tycker allt ser väldigt bra ut! 

Här kommer anmärkningar:
-När man tar bort en applikation får man ett meddelande om att 
applikationen lyckades bli bortagen. Men man får också ett felmeddelande 
som inte verkar relevant "Något oväntat har gått fel, applikationen kan inte hittas i databasen". (Gäller när man är inloggad som admin)

-Inte så mycket kommenterar (dock ej så nödvändigt då koden blir kort och väldigt självförklarande...)

Några av sakerna jag testade som fungerade bra!:
-Snygg.
-kan inte logga in med ogiltiga uppgifter.
-Kan registrera flera applikationer på en användare.
-får varning i fall jag vill ta bort applikationen.
-Får bra relevanta felmeddelanden.
-Bra Admin gränssnitt (kan ta bort användare och deras appar enkelt).
-När jag skriver fel vid registrering så finns mina uppgifter kvar.
-Fungerar bra att ta lägga till applikationer.
-Kommer inte in på "http://localhost:3000/users" med användare som ej är admin.
-Använder inte get för att ta bort en användare utan delete = nice.

10 av 10!

**Comment by 1dv450** [comment]
Bra feedback :+1:

**Comment by al223ec** [comment]
Åtgärdat buggen med felmeddelandet.
