### ISSUE TITLE
Kommentering av ruby koden

### ISSUE THREAD

**Issue by davidsoderberg** [al223ec/1DV450-Registreringsapplikation#11]
Jag skulle även önska att du kommenterade ruby koden lite mer, jag ser att du har kommenterat vissa metoder men inte alla. Kommentera gärna metoder som ligger utanför controllers mappen då dessa är de som är "svårast" att förstå vad de gör.

**Comment by al223ec** [comment]
Ska tänka mer på detta i framtiden
