### ISSUE TITLE
directive templateUrl

### ISSUE THREAD

**Issue by davidsoderberg** [al223ec/1DV450-Registreringsapplikation#13]
Tycker det är smart grej du har gjort med att använda templateUrl istället för att skriva html koden direkt i javascriptet som jag har gjort. Då du separerar html koden och javascripten. Vet du om du får någon prestanda vinst/förlust av att göra på det sättet?

**Comment by al223ec** [comment]
Jag tror att det bör bli en förlust om det blir någon skillnad, bör ju krävas en extra request och kanske något extra metodanrop.

**Comment by davidsoderberg** [comment]
Va tvungen att läsa lite om det och vad jag förstå så laddas de bara in när sidan laddas sen så lagras de i javascripten och kosta därför egentligen inte så mycket mer än att stoppa den direkt i javascripten. Man skall tydligen inte märka någon skillnad på laddningshastigheten om man inte har väldigt många templates.
