### ISSUE TITLE
toerh och controllers module???

### ISSUE THREAD

**Issue by davidsoderberg** [al223ec/1DV450-Registreringsapplikation#14]
Jag ser att du har valt att använda en modul för dina controllers och en module för resten.
Du använder sen dessutom controllers i din toerh module, finns det någon speciell anledning till varför du har valt att lägga din kontrollrar i en separat module ?

**Comment by davidsoderberg** [comment]
Jag brukar dela upp det på resources eller så tillhör all min kod samma module.

**Comment by al223ec** [comment]
Jag har faktiskt inget bra svar, tror att det blev en miss och att jag har tänkt att sätta kontrollerna på toerh modulen.
