### ISSUE TITLE
Peer-review 1

### ISSUE THREAD

**Issue by JenniNord** [al223ec/1DV450-Registreringsapplikation#3]
Hej! Fick äntligen igång applikationen med hjälp av issue #1 som skrevs av den andra som skulle titta på din applikation. Kan vara bra att skriva i README om problemen som har uppstått på windows med din gemfile med tanke på att det lär bli ett återkommande fel.

Gjorde min peer-review av koden som ligger med en release tag.

Det första man slås av när man kör applikationen är hur sjukt snygg den är! Tycker även att det är bra att man som användare kan registrera flera applikationer då detta känns mer verklighetstroget än min egen variant där en utvecklare bara har tillgång till en api-nyckel. Känns också väldigt tryggt att admin kan ta bort användare utifall att användaren missköter alla sina nycklar.

Koden ser lika tjusig ut som applikationen i webbläsaren men om något ska dit så är det kommentarer.

Har samma problem med ett extra felmeddelande när man tar bort en applikation (se issue #1). Och om man ska vara väldigt petig så borde du kolla den pop-up som visas när man vill ta bort en användare. "Du säker?" borde vara "Är du säker?". :)

**Comment by al223ec** [comment]
Hej!
Tack för att du gjorde en peer review trots problem med att få igång allt. Och tack för input, har åtgärdat det extra felmeddelandet =)
