### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by kristofferlind** [al223ec/1DV450-Registreringsapplikation#5]
# Peer review 2
## Installation

Tidigare nämnda problem med bcrypt och sqlite uppstod, förutsatt att inte andra problem uppstår är det nog en bättre lösning att ändra gemfile än att ha instruktioner för det.
## Postman

Samtliga intressanta GET och POST är med, dock saknas PUT och DELETE. För POST används formulärdata istället för json, men även json verkar fungera.

Ett tips är att använda sig av miljövariabler i postman, hittas höger om flikar för auth, nycklarna kan då sättas som en variabel där och det räcker att ändra det på ett ställe.
## Funktion

Jag upplever att API fungerar som det ska och är godkänt, jag har dock kikat lite på registreringsapplikationen också och den skulle må bra av en översyn.
## REST

Principer för både REST och HATEOAS följs.
## Säkerhet

Inte hittat något för API, men i registreringsapplikationen hittade jag två punkter. Det finns ingen authkontroll för att visa en användare och dess nycklar, samt att :index har correct_user_or_admin. :show borde ha correct_user_or_admin och :index admin_user, :destroy borde kanske ligga på correct_user_or_admin. Det enda jag faktiskt testat är att det går att se :show utan att vara inloggad och jag kan ha fel på resten, men se över det.
## Kod

Intressant lösning för att hantera apipunkter mer generiskt. Något bristande kommentering på sina ställen, men överlag en bra balans där det känns som det är mer kommenterarer för kod som är jobbigare att följa. Det är också skiftande indentering, ett tips där är [.editorconfig](http://editorconfig.org/).

Hittade också lite kod där du skriver att du inte är nöjd med lösningen [här](https://github.com/al223ec/1DV450-Registreringsapplikation/blob/master/register_app/app/controllers/api/v1/api_base_controller.rb#L131-L157). JWT kastar undantag för både expire och decodeerror, du kan fånga upp dessa med rescue istället för att ha en massa if-satser.
## Allmänt

Registreringsdelen är riktigt stilig och faker verkar trevligt. Genomtänkt med vad som tillåts via API(jag har helt missat att man inte borde tillåta update/delete på tags) och pluspoäng på att en användare faktiskt kan ha flera applikationer registrerade. En lite trist detalj är att det står "Skapad about 2 hours ago", samt att numreringen på applikationer är sidvis, och inte en total numrering.

Ser också att ratelimiter är påbörjad. Jag använde 'rack-throttle' för det och det var riktigt smidigt.

Lycka till med projektet!

Vänliga hälsningar,
Kristoffer

**Comment by al223ec** [comment]
Fixat buggen med  se :show utan att vara inloggad. Samt sett över felhanteringen.
