### ISSUE TITLE
Strängberoenden

### ISSUE THREAD

**Issue by davidsoderberg** [al223ec/1DV450-Registreringsapplikation#9]
Hej, du använder sträng delen 'http://api.lvh.me:3000' väldigt mycket i din eventService.js och borde läggas i en variabel som används istället.

**Comment by al223ec** [comment]
Ja det håller jag med om, detta bör vara en angular constant likt
.constant("myConfig", {
        "baseUrl": "http://api.lvh.me:3000"
    })
